// Generated by ReScript, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as $$String from "bs-platform/lib/es6/string.js";

function $pipe$great(x, f) {
  return Curry._1(f, x);
}

function dbl(x) {
  return (x << 1);
}

function sqr(x) {
  return Math.imul(x, x);
}

function dbl_sqr_list(lst) {
  return List.map(sqr, List.map(dbl, lst));
}

function string_of_list(pr, lst) {
  return "[" + ($$String.concat(", ", List.map(pr, lst)) + "]");
}

var param = dbl_sqr_list({
      hd: 1,
      tl: {
        hd: 2,
        tl: {
          hd: 3,
          tl: {
            hd: 4,
            tl: /* [] */0
          }
        }
      }
    });

console.log(string_of_list((function (prim) {
            return String(prim);
          }), param));

var l = List.map((function (n) {
        return n + 1 | 0;
      }), {
      hd: 1,
      tl: {
        hd: 2,
        tl: {
          hd: 3,
          tl: /* [] */0
        }
      }
    });

var l2 = dbl_sqr_list({
      hd: 1,
      tl: {
        hd: 5,
        tl: {
          hd: 2,
          tl: /* [] */0
        }
      }
    });

export {
  $pipe$great ,
  dbl ,
  sqr ,
  dbl_sqr_list ,
  string_of_list ,
  l ,
  l2 ,
  
}
/*  Not a pure module */
